baseURL: https://sunnyson.dev/
theme: PaperMod

params:
  images:
    - sun-with-face-emoji.png
  favicon: sun-with-face-emoji.png

  label:
    icon: sun-with-face-emoji.gif
    iconHeight: 30

  cover:
    image: sun-with-face-emoji.png

markup:
  goldmark:
    renderer:
      unsafe: true