title: Sunny's Digital
baseURL: 'https://sunnyson.dev/'
theme: PaperMod

enableRobotsTXT: true
enableEmoji: true

## To enable Google Analytics
# googleAnalytics:

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production

  description: Sunny's website
  author: Sunny Son
  images:
    - sun-with-face-emoji.png
  favicon: favicon.ico

  label:
    text: Sunny's Digital
    icon: /sun-with-face-emoji.gif
    iconHeight: 35

  # Themes params
  DisableLanguageSwitch: false
  TocOpen: true
  TocSide: left
  EnableInstantClick: false
  EnableImageZoom: true
  ShowShareButtons: true
  ShareButtons:
    - linkedin
    - twitter
    - facebook
    - reddit
  ShowCodeCopyButtons: true
  ShowPostNavLinks: true
  Email: sunnys2327@gmail.com

  # Social icon URLs
  socialIcons:
    - name: twitter
      url: "https://twitter.com/__sunnyson__"
    - name: github
      url: "https://github.com/sunnydigital"
    - name: linkedin
      url: "https://www.linkedin.com/in/sunny-son/"
    - name: googlescholar
      url: "https://scholar.google.com/citations?user=tGaMcikAAAAJ&hl=en"
    - name: huggingface
      url: "https://huggingface.co/sunnydigital"
    - name: kaggle
      url: "https://www.kaggle.com/sunnyson"
    - name: rss
      url: "feed.xml"

  socialAccounts:
    twitter:
      username: __sunnyson__
    github:
      username: sunnydigital
    linkedin:
      username: sunny-son
    googlescholar:
      username: Sunny Son
    huggingface:
      username: sunnydigital
    kaggle: 
      username: sunnyson

  profileMode:
    enabled: true
    title: Sunny Son # optional default will be site title
    subtitle: |
      👋 Hi, welcome to my website! 
      
      Here I post some occasional musings, details of projects I'm working on, sentiments on books I'm reading, and my desktop PC creations. 
      
      Thoughts are my own.

    imageUrl: "https://en.gravatar.com/userimage/237046188/62122b946d153a7018b666085c8ae6b1?size=original" # optional
    imageTitle: "Feelin' Sunny" # optional
    imageWidth: 156 # custom size
    imageHeight: 156 # custom size

  hideFooter: false

  cover:
    responsiveImages: false
    linkFullImages: true

  # Shows read time for posts
  ShowReadingTime: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowWordCount: true
  ShowAllPagesInArchive: true

  # Post settings
  post:
    showAuthor: true  # Show the author of posts
    showDate: true  # Show the date of posts
    showTags: true  # Show the tags of posts
    showCover: true  # Show the cover image of posts
    showNextPrev: true  # Show links to the next and previous posts
  
  # Misc
  assets:
    disableHLJS: true
  monoDarkIcon: false
  math: true

  # Analytics site tags
  analytics:
    google:
      SiteVerificationTag: XYZabc
    bing:
      SiteVerificationTag: XYZabc
    yandex:
      SiteVerificationTag: XYZabc

  #editPost:
  #  URL: https://github.com/sunnyson.dev/edit/main/content
  #  Text: Suggest edit
  #  appendFilePath: true

  #commentSystems:
  #  disqus:
  #    shortname: reorx
  #  remark42:
  #    url: https://remark42.reorx.com
  #    site: reorx.github.io
  #  telegramWidget:
  #    channel: reorx_share
  #    accentColor: "9077e1"
  #    limit: 20
  #defaultCommentSystems:
  #  remark42: true

# <!-- ### End of params -->

permalinks:
  notes: /:section/:year/:month/:slugorfilename

# prefer feed.xml rather than index.xml
outputFormats:
  RSS:
    mediatype: application/rss
    baseName: rss

# Manages categories and tags
taxonomies:
  category: categories
  tag: tags

# Changes types of outputs
outputs:
  home:
    - HTML
    - RSS
    - JSON # Necessary

languages:
  en:
    languageName: English

menu:
  main:
    - name: About Me
      url: /aboutme/
      weight: 1
    - name: Notes
      url: /notes/
      weight: 2
    - name: Projects
      url: /projects/
      weight: 3
    - name: Reading
      url: /reading/
      weight: 4
#    - name: PC Builds
#      url: /pcbuilds/
#      weight: 5
#    - name: Newsletter
#      url: /newsletter/
#      weight: 6
    - name: Search
      url: /search/
      weight: 4
    - name: Archives
      url: /archives/
      weight: 5
    - name: Tags
      url: /tags/
      weight: 6
#    - name: FAQ
#      url: /faq/
#      weight: 10
    - name: Web-Sum Plugin
      url: https://web-sum.sunnyson.dev/
      weight: 7

markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    # anchorLineNos: true
    style: dracula
    lineNos: true
    # noClasses: false