title: Sunny's Digital
baseURL: https://sunnyson.dev/
theme: PaperMod

enableRobotsTXT: true
enableEmoji: true

# To enable Google Analytics
googleAnalytics: G-QT6QEKVLDM

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production

  description: Sunny's website
  author: Sunny Son
  images:
    - sun-with-face-emoji.png
  favicon: 
    - sun-with-face-emoji.png

  label:
    text: Sunny's Digital
    icon: sun-with-face-emoji.gif
    iconHeight: 30

  # Themes params
  DisableLanguageSwitch: false
  TocOpen: true
  TocSide: left
  EnableInstantClick: false
  EnableImageZoom: true
  ShowShareButtons: true
  ShareButtons:
    - linkedin
    - twitter
    - facebook
    - reddit
  ShowCodeCopyButtons: true
  ShowPostNavLinks: true
  Email: sunnys2327@gmail.com

  # Social icon URLs
  socialIcons:
    - name: twitter
      url: https://twitter.com/__sunnyson__
    - name: github
      url: https://github.com/sunnydigital
    - name: linkedin
      url: https://www.linkedin.com/in/sunny-son/
    - name: googlescholar
      url: https://scholar.google.com/citations?user=tGaMcikAAAAJ&hl=en
    - name: huggingface
      url: https://huggingface.co/sunnydigital
    - name: kaggle
      url: https://www.kaggle.com/sunnyson
    - name: wandb
      url: https://wandb.ai/sunnyson
    - name: rss
      url: feed.xml

  socialAccounts:
    twitter:
      username: __sunnyson__
    github:
      username: sunnydigital
    linkedin:
      username: sunny-son
    googlescholar:
      username: Sunny Son
    huggingface:
      username: sunnydigital
    kaggle: 
      username: sunnyson
    wandb:
      username: sunnyson

  profileMode:
    enabled: true
    title: Sunny Son # optional default will be site title
    subtitle: |
      👋 Hi, welcome to my website! 
      
      Here I post some occasional musings, details of projects I'm working on, sentiments on books I'm reading, and my desktop PC creations. 
      
      Thoughts are my own.

    imageUrl: https://en.gravatar.com/userimage/237046188/1957e87d84666901ba82a68a32bdfb8c?size=original # optional
    imageTitle: "Feelin' Sunny" # optional
    imageWidth: 156 # custom size
    imageHeight: 156 # custom size

  hideFooter: false

  cover:
    image: sun-with-face-emoji.png
    responsiveImages: false
    linkFullImages: true

  # Shows read time for posts
  ShowReadingTime: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowWordCount: true
  ShowAllPagesInArchive: true

  # Post settings
  post:
    showAuthor: true  # Show the author of posts
    showDate: true  # Show the date of posts
    showTags: true  # Show the tags of posts
    showCover: true  # Show the cover image of posts
    showNextPrev: true  # Show links to the next and previous posts
  
  # Misc
  assets:
    disableHLJS: false
  monoDarkIcon: false
  math: true

  # Analytics site tags (not really sure how to use..?)
  analytics:
    google:
      SiteVerificationTag: XYZabc
    bing:
      SiteVerificationTag: XYZabc
    yandex:
      SiteVerificationTag: XYZabc

  #editPost:
  #  URL: https://github.com/sunnydigital/sunnydigital.github.io/main/content
  #  Text: Suggest edit
  #  appendFilePath: true

  #commentSystems:
  #  disqus:
  #    shortname: reorx
  #  remark42:
  #    url: https://remark42.reorx.com
  #    site: reorx.github.io
  #  telegramWidget:
  #    channel: reorx_share
  #    accentColor: "9077e1"
  #    limit: 20
  #defaultCommentSystems:
  #  remark42: true

# <!-- ### End of params -->

permalinks:
  notes: /:section/:year/:month/:slugorfilename

# prefer feed.xml rather than index.xml
outputFormats:
  RSS:
    mediatype: application/rss
    baseName: rss

# Manages categories and tags
taxonomies:
  category: categories
  tag: tags

# Changes types of outputs
outputs:
  home:
    - HTML
    - RSS
    - JSON # Necessary

languages:
  en:
    languageName: English

menu:
  main:
    - name: About Me
      url: /aboutme/
      weight: 1
    - name: Notes
      url: /notes/
      weight: 2
    - name: Projects
      url: /projects/
      weight: 3
    - name: Reading
      url: /reading/
      weight: 4
    - name: Search
      url: /search/
      weight: 4
    - name: Archives
      url: /archives/
      weight: 5
    - name: Tags
      url: /tags/
      weight: 6
    - name: Web-Sum Plugin
      url: https://web-sum.sunnyson.dev/
      weight: 7

markup:
  goldmark:
    renderer:
      unsafe: true
  # Codeblock parameters
  highlight:
    anchorLineNos: false
    codeFences: true
    guessSyntax: false
    hl_Lines: ""
    hl_inline: false
    lineAnchors: ""
    lineNoStart: 1
    lineNos: true
    lineNumbersInTable: true
    noClasses: true
    noHl: false
    style: monokai
    tabWidth: 2

pygmentsUseClasses:
  true
pygmentsCodefences:
  true