# Site directories
contentDir = "content"
layoutDir = "layouts"
publishDir = "public"

# Site settings
buildDrafts = false
baseURL = 'https://sunnyson.dev/'
canonifyURLs = true
languageCode = 'en-us'
title = "Sunny's Digital"
theme = 'paper'

# Enter your tracking code to enable Google Analytics
googleAnalytics = ''

[params]
    subtitle = "The Personal Website for Sunny Son"
    description = "Sunny's website"
    author = "Sunny Son"

    # Color style
    color = 'light'

    # Header social icons
    twitter = '__sunnyson__'                  # twitter.com/YOUR_TWITTER_ID
    github = 'sunnydigital'                   # github.com/YOUR_GITHUB_ID    
    # instagram = ''                          # instagram.com/YOUR_INSTAGRAM_ID
    linkedin = 'sunny-son'                    # linkedin.com/in/YOUR_LINKEDIN_ID
    # mastodon = ''                           # e.g. 'https://mastodon.instance/@xxx'
    rss = true                                # show rss icon

    # Home page profile
    avatar = 'sunnys2327@gmail.com'           # gravatar email or image url
    name = 'Sunny Son'
    bio = 'CS/DS grad interested in AI/ML; Thoughts are my own (hover over my propic for a surprise)'


    # Misc
    disableHLJS = true                        # disable highlight.js
    monoDarkIcon = false                      # show monochrome dark mode icon
    gravatarCdn = ''                          # e.g. 'https://cdn.v2ex.com/gravatar/'
    graphCommentId = ''                       # use graph comment (disqus alternative)
    math = true                               # enable KaTex math typesetting globally

[taxonomies]
  category = "categories"
  tag = "tags"

[[menu.main]]
  name = "About"
  url = "/about/"
  weight = 1
[[menu.main]]
  name = "Posts"
  url = "/posts/"
  weight = 2
[[menu.main]]
  name = "Projects"
  url = "/projects/"
  weight = 3
[[menu.main]]
  name = "CV"
  url = "/cv/"
  weight = 4
[[menu.main]]
  name = "FAQ"
  url = "/faq/"
  weight = 5
[[menu.main]]
  name = "Readings"
  url = "/readings/"
  weight = 6
[[menu.main]]
  name = "Builds"
  url = "/builds/"
  weight = 7
[[menu.main]]
  name = "Search"
  url = "/search/"
  weight = 8
[[menu.main]]
  name = "Tags"
  url = "/tags/"
  weight = 9