# With much help from https://github.com/jesse-wei/jessewei.dev-PaperMod/blob/main/config.yml
# And 

title: Sunny's Digital
baseURL: 'https://sunnyson.dev/'
theme: PaperModX

enableRobotsTXT: true
enableEmoji: true

params:
  env: production

  description: "Sunny Son's website"
  author: Sunny Son
  images:
    - sun-with-face-emoji.png
  favicon: favicon.ico

  # Themes params
  DisableLanguageSwitch: false
  TocOpen: true
  TocSide: left
  EnableInstantClick: false
  EnableImageZoom: true
  ShowShareButtons: true
  ShareButtons:
    - linkedin
    - twitter
    - facebook
    - reddit
  ShowCodeCopyButtons: true
  ShowPostNavLinks: true
  Email: sunnys2327@gmail.com

  # Social icon URLs
  socialIcons:
    - name: twitter
      url: "https://twitter.com/__sunnyson__"
    - name: github
      url: "https://github.com/sunnydigital"
    - name: linkedin
      url: "https://www.linkedin.com/in/sunny-son/"
    - name: googlescholar
      url: "https://scholar.google.com/citations?user=tGaMcikAAAAJ&hl=en"
    - name: huggingface
      url: "https://huggingface.co/sunnydigital"
    - name: kaggle
      url: "https://www.kaggle.com/sunnyson"
    - name: rss-simple
      url: "feed.xml"

  socialAccounts:
    twitter:
      username: __sunnyson__
    github:
      username: sunnydigital
    linkedin:
      username: sunny-son
    googlescholar:
      username: Sunny Son
    huggingface:
      username: sunnydigital
    kaggle: 
      username: sunnyson

  profileMode:
    enabled: true
    title: Sunny Son # optional default will be site title
    subtitle: |
      👋 Hi, welcome to my website! 
      
      Here I post some occasional musings, details of projects I'm working on, sentiments on books I'm reading, and my desktop PC creations. 
      
      Thoughts are my own.

    imageUrl: "https://en.gravatar.com/userimage/237046188/62122b946d153a7018b666085c8ae6b1?size=original" # optional
    imageTitle: "Feelin' Sunny" # optional
    imageWidth: 128 # custom size
    imageHeight: 128 # custom size  


  # Shows read time for posts
  ShowReadingTime: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowWordCount: true
  ShowAllPagesInArchive: true

  # Post settings
  post:
    showAuthor: true  # Show the author of posts
    showDate: true  # Show the date of posts
    showTags: true  # Show the tags of posts
    showCover: true  # Show the cover image of posts
    showNextPrev: true  # Show links to the next and previous posts
  
  # Misc
  disableHLJS: true
  monoDarkIcon: false
  math: true

  #commentSystems:
  #  disqus:
  #    shortname: reorx
  #  remark42:
  #    url: https://remark42.reorx.com
  #    site: reorx.github.io
  #  telegramWidget:
  #    channel: reorx_share
  #    accentColor: "9077e1"
  #    limit: 20
  #defaultCommentSystems:
  #  remark42: true

permalinks:
  notes: /:section/:year/:month/:slugorfilename

# prefer feed.xml rather than index.xml
outputFormats:
  RSS:
    mediatype: "application/rss"
    baseName: "feed"

# Manages categories and tags
taxonomies:
  category: categories
  tag: tags

# Changes types of outputs
outputs:
  home:
    - HTML
    - RSS
    - JSON # Necessary

languages:
  en:
    languageName: "English"

menu:
  main:
    - name: About Me
      url: /aboutme/
      weight: 1
    - name: Posts
      url: /posts/
      weight: 2
    - name: Projects
      url: /projects/
      weight: 3
    - name: Readings
      url: /readings/
      weight: 4
    - name: PC Builds
      url: /pcbuilds/
      weight: 5
#    - name: Newsletter
#      url: /newsletter/
#      weight: 6
    - name: Search
      url: /search/
      weight: 6
    - name: Archives
      url: /archives/
      weight: 7
    - name: Tags
      url: /tags/
      weight: 8
#    - name: FAQ
#      url: /faq/
#      weight: 10

markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    style: dracula
    lineNos: false
    noClasses: false
