## With much help from https://github.com/jesse-wei/jessewei.dev-PaperMod/blob/main/config.yml

# Site directories
contentDir: content
layoutDir: layouts
publishDir: public

# Build drafts
buildDrafts: false
baseURL: 'https://sunnyson.dev/'
canonifyURLs: true
languageCode: en-us
title: Sunny's Digital
theme: PaperMod
# paginate: 10

# Robots and build information
enableRobotsTXT: true
buildDrafts: true
buildFuture: false
buildExpired: false
pluralizeListTitles: false

# Enter your tracking code to enable Google analytics
googleAnalytics: ''

# Home page config
params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.

  profileMode:
    enabled: true
    title: Sunny Son # optional default will be site title
    subtitle: "👋 Hi, welcome to my website! Here I post some occasional musings, details of projects I'm working on, sentiments on books I'm reading, and my desktop PC creations. Thoughts are my own."
    imageUrl: "https://en.gravatar.com/userimage/237046188/62122b946d153a7018b666085c8ae6b1?size=original" # optional
    imageTitle: "Feelin' Sunny" # optional
    imageWidth: 128 # custom size
    imageHeight: 128 # custom size

  # Social icon URLs
  socialIcons:
    - name: "twitter"
      title: "Twitter"
      url: "https://twitter.com/__sunnyson__"
    - name: "github"
      title: "GitHub"
      url: "https://github.com/sunnydigital"
    - name: "linkedin"
      title: "LinkedIn"
      url: "https://www.linkedin.com/in/sunny-son/"
    - name: "googlescholar"
      title: "Google Scholar"
      url: "https://scholar.google.com/citations?user=tGaMcikAAAAJ&hl=en"
    - name: "huggingface"
      title: "Hugging Face"
      url: "https://huggingface.co/sunnydigital"
    - name: "kaggle"
      title: "Kaggle"
      url: "https://www.kaggle.com/sunnyson"

  # Logo and name shown on top left of site
  label:
    text: # "Sunny's Website"
    icon: # /static/favicon.ico
    iconHeight: # 35

  # Image displayed when sharing website link
  images: ["static/sun-with-face-emoji.png"]

  # Share button on posts
  shareButtons: ["linkedin", "twitter", "facebook", "reddit"]
  ShowShareButtons: true

  # Shows read time for posts
  ShowReadingTime: true

  # Shows breadcrumbs
  ShowBreadCrumbs: true

  # Allow copy button for code
  ShowCodeCopyButtons: true

  # Shows RSS Button
  ShowRssButtonInSectionTermList: true

  # Shows word count or not
  ShowWordCount: false

  # Show TOC (Table of Contents)
  showtoc: true
  tocopen: true

  # Show TOC, scrolling, on left side
  TocSide: "left"

  # Changes Archive to show all posts
  ShowAllPagesInArchive: true

  # Generation of images and hyperlinks
  cover:
    responsiveImages: true
    linkFullImages: true

  # Theme settings
  defaultTheme: auto
  disableThemeToggle: false

  # Post settings
  post:
    showAuthor: true  # Show the author of posts
    showDate: true  # Show the date of posts
    showTags: true  # Show the tags of posts
    showCover: true  # Show the cover image of posts
    showNextPrev: true  # Show links to the next and previous posts
  # Footer settings
  footercontent: "Copyright © 2023 Sunny Son Powered by Chips and Caffeine"  # The copyright notice to show in the footer
  
  social:
    twitter: "__sunnyson__"  # Your Twitter username
    github: "sunnydigital"  # Your GitHub username
    linkedin: "sunny-son"
    email: "sunnys2327@gmail.com"  # Your email address

  # Misc
  disableHLJS: true
  monoDarkIcon: false
  gravatarCdn: ''
  graphCommentId: ''
  math: true

# Manages categories and tags
taxonomies:
  category: categories
  tag: tags

# Changes types of outputs
outputs:
  home:
    - HTML
    - RSS
    - JSON # Necessary

# Sets menu items (URL links)
menu:
  main:
    - name: About
      url: /about/
      weight: 1
    - name: Posts
      url: /posts/
      weight: 2
    - name: Projects
      url: /projects/
      weight: 3
    - name: Readings
      url: /readings/
      weight: 4
    - name: PC Builds
      url: /pcbuilds/
      weight: 5
    - name: Search
      url: /search/
      weight: 6
    - name: Archives
      url: /archives/
      weight: 7
    - name: Tags
      url: /tags/
      weight: 8
    - name: FAQ
      url: /faq/
      weight: 9

#  footer:
#    - name: Privacy Policy
#      url: /privacy/
#      weight: 1
#    - name: Terms of Service
#      url: /terms/
#      weight: 2