# Site directories
contentDir: content
layoutDir: layouts
publishDir: public

# Build drafts
buildDrafts: false
baseURL: 'https://sunnyson.dev/'
canonifyURLs: true
languageCode: en-us
title: Sunny's Digital
theme: PaperMod

# Enter your tracking code to enable Google analytics
googleAnalytics: ''

# Home page config
params:
  profileMode:
    enabled: true
    title: Sunny's Digital # optional default will be site title
    subtitle: "Hi! Welcome to my website! (Thoughts are my own)"
    imageUrl: "https://en.gravatar.com/userimage/237046188/62122b946d153a7018b666085c8ae6b1?size=original" # optional
    imageTitle: "Feelin' Sunny" # optional
    imageWidth: 120 # custom size
    imageHeight: 120 # custom size

  # Social icon URLs
  socialIcons:
    - name: "Twitter"
      url: "https://twitter.com/__sunnyson__"
    - name: "GitHub"
      url: "https://github.com/sunnydigital"
    - name: "LinkedIn"
      url: "https://www.linkedin.com/in/sunny-son/"
    - name: "Google Scholar"
      url: "https://scholar.google.com/citations?user=tGaMcikAAAAJ&hl=en"
  
  # Share button on posts
  ShowShareButtons: true

  # Shows read time for posts
  ShowReadingTime: true

  # Shows breadcrumbs
  ShowBreadCrumbs: true

  # Allow copy button for code
  ShowCodeCopyButtons: true

  # Generation of images and hyperlinks
  cover:
    responsiveImages: true
    linkFullImages: true

  # Theme settings
  defaultTheme: auto
  disableThemeToggle: false

  # Misc
  disableHLJS: true
  monoDarkIcon: false
  gravatarCdn: ''
  graphCommentId: ''
  math: true

taxonomies:
  category: categories
  tag: tags

outputs:
  home:
    - HTML
    - RSS
    - JSON # Necessary

menu:
  main:
    - name: About
      url: /about/
      weight: 1
    - name: Posts
      url: /posts/
      weight: 2
    - name: Projects
      url: /projects/
      weight: 3
    - name: CV
      url: /cv/
      weight: 4
    - name: Readings
      url: /readings/
      weight: 5
    - name: Builds
      url: /builds/
      weight: 6
    - name: Search
      url: /search/
      weight: 7
    - name: Archive
      url: /archive/
      eright: 8
    - name: Tags
      url: /tags/
      weight: 9
    - name: FAQ
      url: /faq/
      weight: 10